# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import search_pb2 as search__pb2


class SearchCarsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCar = channel.unary_unary(
                '/cars.SearchCars/GetCar',
                request_serializer=search__pb2.GetCarRequest.SerializeToString,
                response_deserializer=search__pb2.Car.FromString,
                )


class SearchCarsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchCarsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCar,
                    request_deserializer=search__pb2.GetCarRequest.FromString,
                    response_serializer=search__pb2.Car.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cars.SearchCars', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchCars(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cars.SearchCars/GetCar',
            search__pb2.GetCarRequest.SerializeToString,
            search__pb2.Car.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
