# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x04\x63\x61rs\"\x1f\n\x03\x43\x61r\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1b\n\rGetCarRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x36\n\nSearchCars\x12(\n\x06GetCar\x12\x13.cars.GetCarRequest\x1a\t.cars.Carb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CAR']._serialized_start=22
  _globals['_CAR']._serialized_end=53
  _globals['_GETCARREQUEST']._serialized_start=55
  _globals['_GETCARREQUEST']._serialized_end=82
  _globals['_SEARCHCARS']._serialized_start=84
  _globals['_SEARCHCARS']._serialized_end=138
# @@protoc_insertion_point(module_scope)
